var arrLang = {
  'hu': {
    'menuitem-1': 'rólunk',
    'menuitem-2': 'munkáink',
    'main': 'mi vagyunk a winkler',
    'quote': 'gondolkodjunk együtt előremutató megoldásokon',
    'act-head-1': 'Tervezünk és újragondolunk',
    'act-text-1': 'Print és online felületeket készítünk, amelyek segítenek neked a lehető legjobb ügyfélélmény elérésében.',
    'act-head-2': 'Márkát építünk',
    'act-text-2': 'Megoldásokat kutatunk, hogyan tedd még vonzóbbá és könnyebben használhatóvá szolgáltatásodat ügyfeleid számára.',
    'act-head-3': 'Nagy adatmennyiségből készítünk kiadványokat',
    'act-text-3': 'Átgondolt és kipróbált automatizálási folyamataink segítségével pontosan és gyorsan készítünk kiadványokat.',
    'recent-work': 'a legújabbak',
    'team-head': 'a csapat',
    'guszti': 'Szakács Gusztáv Bálint',
    'guszti-tags': '#can-do-attitude #kertészkedés #kommunikáció #felhasználóközpontú #design',
    'dani': 'Taskó Dániel',
    'dani-tags': '#felhasználóközpontú_tervezés #újragondolás #vizualizáció #unikornis',
    'eszter': 'Tatay Eszter',
    'eszter-tags': '#tipográfia #fantasy #fotomanip #StephenKing #retus',
    'andris': 'Demcsák András',
    'andris-tags': '#hézagmentesillesztés #éjszakaiműszak #solutioneer #transporter #kütyük',
    'bori': 'Ficzere Adrienn',
    'bori-tags': '#Front-end-design #kutatás #gondolatolvasás #britpop',
    'balu': 'Pesti Balázs',
    'balu-tags': '#aranymetszet #aprórészletek #természetesen #süti #Dunakanyar',
    'contact-head': 'kapcsolat',
    'location': 'Találj meg!',
    'agency': 'Stenzel kreatívügynökség',
    'address': '1111 Budapest, Lágymányosi utca 20.',
    'contact': 'Beszélgessünk!',
    'international': 'Nemzetköziek vagyunk:',
    'winklergroup': 'A Winkler&Stenzel csoport'
  },

  'de': {
    'menuitem-1': 'agentur',
    'menuitem-2': 'portfolio',
    'main': 'wir sind winkler',
    'quote': 'Lassen Sie uns gemeinsam nach der besten Lösung für Ihr Unternehmen oder Ihr Produkt suchen!',
    'act-head-1': 'Wir planen, entwickeln und realisieren',
    'act-text-1': 'Marketing-Konzepte und Kreationen in Digital und Print - für ein ideales Kundenerlebnis',
    'act-head-2': 'Wir machen Marken',
    'act-text-2': 'Wir suchen nach Lösungen mit denen Sie erfolgreich den ungarischen Markt erobern können',
    'act-head-3': 'Schneller, leichter, zuverlässiger',
    'act-text-3': 'Mit unseren erprobten Tools zur automatisierten Medienproduktion, können wir Ihre Prospekte, Kataloge oder Preislisten zukünftig schneller und effizienter produzieren',
    'recent-work': 'aktuell',
    'team-head': 'Das Team',
    'guszti': 'Gusztav Balint Szakacs',
    'guszti-tags': '#can-do-attitude #Gartenarbeit #Kommunikation #Benutzerorientiert #design',
    'dani': 'Daniel Tasko',
    'dani-tags': '#user-centered-design #rethink #Visualisierung #unicorn',
    'eszter': 'Eszter Tatay',
    'eszter-tags': '#Typographie #fantasy #photomanip #StephenKing #Retusche',
    'andris': 'Andras Demcsak',
    'andris-tags': '#hézagmentesillesztés #Nachtschicht #solutioneer #transporter #kütyük',
    'bori': 'Adrienn Ficzere',
    'bori-tags': '#front-end-design #Forschung #Gedanklesen #britpop',
    'balu': 'Balazs Pesti',
    'balu-tags': '#goldenratio #tinydetails #naturally #Kuchen #Dunakanyar',
    'contact-head': 'Kontakt',
    'location': 'Finden Sie uns!',
    'agency': 'Stenzel Kreativ Agentur',
    'address': '20. Lágymányosi str., Budapest 1111',
    'contact': 'Wir freuen uns auf eine Nachricht!',
    'international': 'Wir sind international:',
    'winklergroup': 'Winkler&Stenzel group'
  },

  'en': {
    'menuitem-1': 'about',
    'menuitem-2': 'work',
    'main': 'we are winkler',
    'quote': 'we are hard working and easy going',
    'act-head-1': 'Design & rethink',
    'act-text-1': 'We design for print and online helping you and your customers to achieve the best user experience.',
    'act-head-2': 'Branding',
    'act-text-2': 'We are looking for solutions to do your service more efficient.',
    'act-head-3': 'We create stunnig layouts from big data',
    'act-text-3': 'Átgondolt és kipróbált automatizálási folyamataink segítségével pontosan és gyorsan készítünk kiadványokat.',
    'recent-work': 'recents',
    'team-head': 'the team',
    'guszti': 'Gusztav Balint Szakacs',
    'guszti-tags': '#can-do-attitude #gardening #communication #user-centered #design',
    'dani': 'Daniel Tasko',
    'dani-tags': '#user-centered-design #rethink #visualization #unicorn',
    'eszter': 'Eszter Tatay',
    'eszter-tags': '#typography #fantasy #photomanip #StephenKing #retouch',
    'andris': 'Andras Demcsak',
    'andris-tags': '#hézagmentesillesztés #éjszakaiműszak #solutioneer #transporter #kütyük',
    'bori': 'Adrienn Ficzere',
    'bori-tags': '#front-end-design #research #mind-reading #britpop',
    'balu': 'Balazs Pesti',
    'balu-tags': '#goldenratio #tinydetails #naturally #cookie #Dunakanyar',
    'contact-head': 'contact us',
    'location': 'Find us!',
    'agency': 'Stenzel creative group',
    'address': '20. Lágymányosi str., Budapest 1111',
    'contact': 'Say something!',
    'international': 'We are international:',
    'winklergroup': 'Winkler&Stenzel group'
  }
};

$(function () {
  $('.translate').click(function() {
    var lang = $(this).attr('id');

    $('.lang').each(function (index, element) {
      $(this).text(arrLang[lang][$(this).attr('key')]);
    });
  });
});
